server {
    listen 80;
    server_name matchinmobiliario.fcadev.cl;
    root /usr/share/nginx/html;
    index index.html;

    location = /api/docs {
        alias /usr/share/nginx/html/api-docs.html;
        default_type text/html;
    }

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
